### PR TITLE
Throw login exception in preLogin instead of sleep

### LINKED ISSUE #18: Fix indentation mistakes according to Coding Style & General Guidelines
Tab size is 8 space length in some files. It should be 4.

### PR DESCRIPTION
**Pull request by karakayasemi**
Brute force settings now configurable.
Sleep is removed, #12 
Ip will be blocked after too many failed attempts #11
admin settings style is enhanced #7 
Indentation mistakes are fixed #18

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
bildschirmfoto von 2017-08-21 10-22-34

Some styling on the input fields is missing

File: js/settings-admin.js [hunk 1]
```diff
@@ -19,24 +19,38 @@
...
+            var banPeriod = $('#security-bfp-ban-period').val();
+            if($.isNumeric(thresholdTime) && thresholdTime>0 &&
+                $.isNumeric(failTolerance) && failTolerance>0 &&
+                $.isNumeric(banPeriod) && banPeriod>0) {
+                OC.AppConfig.setValue('security', 'brute_force_protection_time_threshold', thresholdTime);
+                OC.AppConfig.setValue('security', 'brute_force_protection_fail_tolerance', failTolerance);
+                OC.AppConfig.setValue('security', 'brute_force_protection_ban_period', banPeriod);
+                OC.msg.finishedSuccess('#security-save-bfp-settings-message', OC.L10N.translate('Security', 'Preferences are saved'));
+            } else {
+                OC.msg.finishedError('#security-save-bfp-settings-message', OC.L10N.translate('Security', 'Inputs are should be positive integer'));
```
Comment (phil-davis) [inline js/settings-admin.js]: Inputs must be positive integers

File: lib/SecurityConfig.php [hunk 2]
```diff
@@ -57,17 +59,45 @@ public function getAllSecurityConfigs() {
...
-			'enable_brute_force_protection',
-			'0'
+			'brute_force_protection_fail_tolerance',
+			'3'
+		);
+		return intval($tolerance);
+	}
+
+	/**
+	 * Look failed login attempts in how many seconds?
```
Comment (phil-davis) [inline lib/SecurityConfig.php]: Count failed login attempts over how many seconds

File: lib/SecurityConfig.php [hunk 3]
```diff
@@ -57,17 +59,45 @@ public function getAllSecurityConfigs() {
...
+		$timeThreshold = $this->config->getAppValue(
+			'security',
+			'brute_force_protection_time_threshold',
+			'600'
+		);
+		return intval($timeThreshold);
+	}
+
+	/**
+	 * How many seconds ban attacker
```
Comment (phil-davis) [inline lib/SecurityConfig.php]: How many seconds to ban an attacker

File: templates/settings-admin.php [hunk 4]
```diff
@@ -21,22 +21,27 @@
...
-<div id="brute-force-protection">
-	<div>
-		<input type="checkbox" class="checkbox" id="security-brute-force-protection-enabled"
-			<?php if ($_['isBruteForceProtectionEnabled']) p("checked");?> >
-		<label for="security-brute-force-protection-enabled"><?php p($l->t('Activate Brute Force Protection')) ?></label>
+<div id="security-brute-force-protection" class="section">
+    <h2 class="inlineblock"><?php p($l->t('Brute Force Protection')); ?></h2>
+    <span id="security-save-bfp-settings-message" class="msg"></span>
+    <div>
+        <label for="security-bfp-threshold-time"><?php p($l->t('Look failed login attempts in how many seconds?')) ?></label><br>
```
Comment (phil-davis) [inline templates/settings-admin.php]: Count failed login attempts over how many seconds?

File: js/settings-admin.js [hunk 5]
```diff
@@ -19,24 +19,38 @@
...
+            var thresholdTime = $('#security-bfp-threshold-time').val();
+            var failTolerance = $('#security-bfp-fail-tolerance').val();
+            var banPeriod = $('#security-bfp-ban-period').val();
+            if($.isNumeric(thresholdTime) && thresholdTime>0 &&
+                $.isNumeric(failTolerance) && failTolerance>0 &&
+                $.isNumeric(banPeriod) && banPeriod>0) {
+                OC.AppConfig.setValue('security', 'brute_force_protection_time_threshold', thresholdTime);
+                OC.AppConfig.setValue('security', 'brute_force_protection_fail_tolerance', failTolerance);
+                OC.AppConfig.setValue('security', 'brute_force_protection_ban_period', banPeriod);
+                OC.msg.finishedSuccess('#security-save-bfp-settings-message', OC.L10N.translate('Security', 'Preferences are saved'));
```
Comment (DeepDiver1975) [inline js/settings-admin.js]: please use t() instead of OC.L10N.translate - only using t() the extraction tool can extract strings - THX

File: tests/Db/DbServiceTest.php [hunk 6]
```diff
@@ -49,7 +53,10 @@ public function setUp() {
 
         $this->connection = \OC::$server->getDatabaseConnection();
         $this->factory = new TimeFactory();
-        $this->dbService = new DbService($this->connection, $this->factory);
+        $this->configMock = $this->getMockBuilder('OCA\Security\SecurityConfig')
```
Comment (DeepDiver1975) [inline tests/Db/DbServiceTest.php]: Just comment for the future use:

```php
SecurityConfig::class

File: tests/HooksTest.php [hunk 7]
```diff
@@ -70,34 +70,31 @@ public function setUp() {
...
         $this->passwordValidatorMock = $this->getMockBuilder('OCA\Security\PasswordValidator')
-			->disableOriginalConstructor()
-			->getMock();
-		$this->dispatcherMock = $this->getMockBuilder('Symfony\Component\EventDispatcher\EventDispatcher')
-			->disableOriginalConstructor()
-			->getMock();
-
+            ->disableOriginalConstructor()
+            ->getMock();
+        $this->dispatcherMock = $this->getMockBuilder('Symfony\Component\EventDispatcher\EventDispatcher')
```
Comment (DeepDiver1975) [inline tests/HooksTest.php]: ::class - see above

**Comment by DeepDiver1975** [comment]
Please use rebase instead of merge
1. git fetch origin -p
2. git rebase -i origin/master
3. editor pops up - review commits and adjust if necessary - save and close
4. resolve conflicts if necessary (basically follow instructions as printed by git)
5. push branch

**Comment by karakayasemi** [comment]
@DeepDiver1975 any obstacle?
